// Generated by scripts/update-verified-data.mjs
// This file records source checks. It does not turn unverified source changes into game facts.

export const sourceWatch = [
  {
    "label": "Roblox game page",
    "url": "https://www.roblox.com/games/79268393072444",
    "trust": "official",
    "use": "Game description, update notes, codes, badges, keys, and gamepasses when visible.",
    "ok": true,
    "status": 200,
    "checkedAt": "2026-09-18T05:32:55.755Z",
    "responseMs": 1085,
    "contentLength": 34360,
    "hash": "d94c40888afb9f0001efec9945447b4f0e2ff3229f961faf7c98e4dd66197912",
    "changed": true
  },
  {
    "label": "Google Trends manual lead",
    "url": "https://trends.google.com/trends/explore?q=Sell%20Lemons",
    "trust": "lead",
    "use": "Search demand only; never a source for game facts.",
    "ok": false,
    "status": 429,
    "checkedAt": "2026-09-18T05:32:55.903Z",
    "responseMs": 148,
    "contentLength": 465,
    "hash": "1e0b1aaee4c321f7ae0b3b216083295947f578dfed3dca124cdae8e0d3854259",
    "changed": false
  }
] as const

export function getLastSourceCheckDate(): string {
  return 'September 18, 2026'
}
