// Generated by scripts/update-verified-data.mjs
// This file records source checks. It does not turn unverified source changes into game facts.

export const sourceWatch = [
  {
    "label": "Roblox game page",
    "url": "https://www.roblox.com/games/79268393072444",
    "trust": "official",
    "use": "Game description, update notes, codes, badges, keys, and gamepasses when visible.",
    "ok": true,
    "status": 200,
    "checkedAt": "2026-08-13T03:25:26.079Z",
    "responseMs": 654,
    "contentLength": 34748,
    "hash": "1226a99b4f8002eb35ca41d98407898e30434e0cc1361e23bb8089f368a8c683",
    "changed": true
  },
  {
    "label": "Google Trends manual lead",
    "url": "https://trends.google.com/trends/explore?q=Sell%20Lemons",
    "trust": "lead",
    "use": "Search demand only; never a source for game facts.",
    "ok": false,
    "status": 429,
    "checkedAt": "2026-08-13T03:25:26.358Z",
    "responseMs": 279,
    "contentLength": 465,
    "hash": "1e0b1aaee4c321f7ae0b3b216083295947f578dfed3dca124cdae8e0d3854259",
    "changed": false
  }
] as const

export function getLastSourceCheckDate(): string {
  return 'August 13, 2026'
}
