// Generated by scripts/update-verified-data.mjs
// This file records source checks. It does not turn unverified source changes into game facts.

export const sourceWatch = [
  {
    "label": "Roblox game page",
    "url": "https://www.roblox.com/games/79268393072444",
    "trust": "official",
    "use": "Game description, update notes, codes, badges, keys, and gamepasses when visible.",
    "ok": true,
    "status": 200,
    "checkedAt": "2026-06-11T05:27:25.407Z",
    "responseMs": 326,
    "contentLength": 33741,
    "hash": "ad4ffb65524761151595c47cf368b11d6f8b9cb3907bee6729c923cad2df3af9",
    "changed": true
  },
  {
    "label": "Google Trends manual lead",
    "url": "https://trends.google.com/trends/explore?q=Sell%20Lemons",
    "trust": "lead",
    "use": "Search demand only; never a source for game facts.",
    "ok": false,
    "status": 429,
    "checkedAt": "2026-06-11T05:27:25.509Z",
    "responseMs": 101,
    "contentLength": 465,
    "hash": "1e0b1aaee4c321f7ae0b3b216083295947f578dfed3dca124cdae8e0d3854259",
    "changed": false
  }
] as const

export function getLastSourceCheckDate(): string {
  return 'June 11, 2026'
}
