// Generated by scripts/update-verified-data.mjs
// Official Roblox API data used to unlock verified site content.

export const robloxGame = {
  "id": 7395930870,
  "placeId": 79268393072444,
  "name": "[🛸] Sell Lemons 🍋",
  "description": "Sell Lemons 🍋. Make 💵💰🤑.\n\n🍋 Sell Lemons\n💵 Earn lots of cash\n💪 Unlock unique powers\n👽 Make lucrative deals\n🌌 Enter the %^REDACTED*$!\n\n❓ Did you know... You continue to earn 100% of your income offline! 💰\n\n👍 Like the game and join our community to receive absolutely nothing at all!*\n*Except for the knowledge that you made the developers very happy. :)",
  "creatorName": "BloxByte Games",
  "creatorType": "Group",
  "playing": 16857,
  "visits": 398683797,
  "favoritedCount": 421491,
  "maxPlayers": 10,
  "created": "2025-03-17T23:31:17.017Z",
  "updated": "2026-08-03T15:11:48.1596188Z",
  "genre": "Simulation",
  "subgenre": "Tycoon",
  "canonicalUrlPath": "/games/79268393072444/Sell-Lemons",
  "checkedAt": "2026-08-04T04:11:50.576Z"
} as const

export const robloxVotes = {
  "upVotes": 316687,
  "downVotes": 17329,
  "checkedAt": "2026-08-04T04:11:50.576Z"
} as const

export const robloxBadges = [
  {
    "id": 2839799180453288,
    "name": "Sell Lemons",
    "description": "Buy the Lemon Stand. — \"Lemonade? Nah, we Sell Lemons™.\"",
    "enabled": true,
    "created": "2026-05-13T21:20:19.576+00:00",
    "updated": "2026-05-13T21:20:19.576+00:00",
    "awardedCount": 42711884,
    "pastDayAwardedCount": 120060,
    "winRatePercentage": 0.277
  },
  {
    "id": 798229121420564,
    "name": "Lemon Delivery",
    "description": "Buy LemonDash. — \"Lemons, now conveniently delivered!\"",
    "enabled": true,
    "created": "2026-05-13T21:21:02.153+00:00",
    "updated": "2026-05-13T21:21:02.153+00:00",
    "awardedCount": 38435579,
    "pastDayAwardedCount": 104917,
    "winRatePercentage": 0.242
  },
  {
    "id": 1670501100924687,
    "name": "Wholesale Lemons",
    "description": "Buy Lemon Depot. — \"Time to go wholesale.\"",
    "enabled": true,
    "created": "2026-05-13T21:21:18.539+00:00",
    "updated": "2026-05-13T21:21:18.539+00:00",
    "awardedCount": 29959173,
    "pastDayAwardedCount": 80886,
    "winRatePercentage": 0.187
  },
  {
    "id": 846427648664068,
    "name": "Lemon Trading",
    "description": "Buy Lemon Trading. — \"We're going to BE the market...\"",
    "enabled": true,
    "created": "2026-05-13T21:21:38.422+00:00",
    "updated": "2026-05-13T21:21:38.422+00:00",
    "awardedCount": 18053713,
    "pastDayAwardedCount": 45411,
    "winRatePercentage": 0.105
  },
  {
    "id": 239648239068938,
    "name": "Advanced Lemons",
    "description": "Buy Lemon Labs. — \"People are getting tired of boring old lemons. We must innovate!\"",
    "enabled": true,
    "created": "2026-05-13T21:21:57.039+00:00",
    "updated": "2026-05-13T21:21:57.039+00:00",
    "awardedCount": 8537360,
    "pastDayAwardedCount": 24187,
    "winRatePercentage": 0.056
  },
  {
    "id": 4335425379555311,
    "name": "Really Advanced Lemons",
    "description": "Buy Lemon Robotics. — \"It's the natural progression, really.\"",
    "enabled": true,
    "created": "2026-05-13T21:22:25.757+00:00",
    "updated": "2026-05-13T21:22:25.757+00:00",
    "awardedCount": 4903304,
    "pastDayAwardedCount": 16294,
    "winRatePercentage": 0.038
  },
  {
    "id": 1961627089785243,
    "name": "Lemon-Based Government",
    "description": "Buy Lemon Republic. — \"You know who never pays taxes? The government. ...Wait, I have an idea.\"",
    "enabled": true,
    "created": "2026-05-13T21:23:27.607+00:00",
    "updated": "2026-05-13T21:23:27.607+00:00",
    "awardedCount": 2721514,
    "pastDayAwardedCount": 11170,
    "winRatePercentage": 0.026
  },
  {
    "id": 1703862948070410,
    "name": "Interstellar Lemons",
    "description": "Buy LemonX. — \"Picture this:  Lemons. In. Space.\"",
    "enabled": true,
    "created": "2026-05-13T21:23:45.522+00:00",
    "updated": "2026-05-13T21:23:45.522+00:00",
    "awardedCount": 1318747,
    "pastDayAwardedCount": 6913,
    "winRatePercentage": 0.016
  },
  {
    "id": 4440938742680782,
    "name": "Millionaire",
    "description": "Reach a cash balance of $1,000,000. — \"Who knew lemons were so popular?\"",
    "enabled": true,
    "created": "2026-05-13T21:24:46.557+00:00",
    "updated": "2026-05-13T21:24:46.557+00:00",
    "awardedCount": 36314495,
    "pastDayAwardedCount": 98953,
    "winRatePercentage": 0.229
  },
  {
    "id": 1896495343286922,
    "name": "Billionaire",
    "description": "Reach a cash balance of $1,000,000,000. — \"I'm in the big leagues now!\"",
    "enabled": true,
    "created": "2026-05-13T21:25:10.313+00:00",
    "updated": "2026-05-13T21:25:10.313+00:00",
    "awardedCount": 32780888,
    "pastDayAwardedCount": 88943,
    "winRatePercentage": 0.205
  },
  {
    "id": 3733621909108985,
    "name": "Trillionaire",
    "description": "Reach a cash balance of $1,000,000,000,000. — \"We're just getting started...\"",
    "enabled": true,
    "created": "2026-05-13T21:25:38.477+00:00",
    "updated": "2026-05-13T21:27:56.828+00:00",
    "awardedCount": 28160857,
    "pastDayAwardedCount": 75526,
    "winRatePercentage": 0.174
  },
  {
    "id": 3422658647150754,
    "name": "Decillionaire",
    "description": "Reach a cash balance of $1,000,000,000,000,000,000,000,000,000,000,000. — \"Now that's a lot of zeroes.\"",
    "enabled": true,
    "created": "2026-05-13T21:35:27.148+00:00",
    "updated": "2026-05-13T21:35:27.148+00:00",
    "awardedCount": 6378157,
    "pastDayAwardedCount": 19608,
    "winRatePercentage": 0.045
  },
  {
    "id": 2539875741824246,
    "name": "Vigintillionaire",
    "description": "Reach a cash balance of $1 vigintillion. — \"The zeroes are simply absurd now.\"",
    "enabled": true,
    "created": "2026-05-13T21:35:54.939+00:00",
    "updated": "2026-05-13T21:35:54.939+00:00",
    "awardedCount": 2014330,
    "pastDayAwardedCount": 8836,
    "winRatePercentage": 0.02
  },
  {
    "id": 2219643958762445,
    "name": "Trigintillionaire",
    "description": "Reach a cash balance of $1 trigintillion. — \"...Am I triggering something?\"",
    "enabled": true,
    "created": "2026-05-13T21:36:14.723+00:00",
    "updated": "2026-05-13T21:36:14.723+00:00",
    "awardedCount": 783161,
    "pastDayAwardedCount": 4685,
    "winRatePercentage": 0.011
  },
  {
    "id": 752572950495939,
    "name": "Quattuorquinquagintillionaire",
    "description": "Reach a cash balance of $1 quattuorquinquagintillion. — \"Okay, come on. This can't be a real number.\"",
    "enabled": true,
    "created": "2026-05-13T21:37:44.736+00:00",
    "updated": "2026-05-13T21:37:44.736+00:00",
    "awardedCount": 360751,
    "pastDayAwardedCount": 2936,
    "winRatePercentage": 0.007
  },
  {
    "id": 3040495340594119,
    "name": "Centillionaire",
    "description": "Reach a cash balance of $1 centillion. — \"Another day, another dollar.\"",
    "enabled": true,
    "created": "2026-05-13T21:38:58.774+00:00",
    "updated": "2026-05-13T21:38:58.774+00:00",
    "awardedCount": 29643,
    "pastDayAwardedCount": 455,
    "winRatePercentage": 0.001
  },
  {
    "id": 4386641676887762,
    "name": "Powered Up",
    "description": "Unlock your first power. — \"Feels a bit tingly. ...I like it.\"",
    "enabled": true,
    "created": "2026-05-13T21:41:07.025+00:00",
    "updated": "2026-05-13T21:41:07.025+00:00",
    "awardedCount": 11374648,
    "pastDayAwardedCount": 24638,
    "winRatePercentage": 0.057
  },
  {
    "id": 1527780026429423,
    "name": "Ultimate Power",
    "description": "Fully unlock every power. — \"POWER! Mwahahaha!\"",
    "enabled": true,
    "created": "2026-05-13T21:41:23.56+00:00",
    "updated": "2026-05-13T21:41:23.56+00:00",
    "awardedCount": 238314,
    "pastDayAwardedCount": 2125,
    "winRatePercentage": 0.005
  },
  {
    "id": 606453995581949,
    "name": "Out of this World",
    "description": "Obtain your first extraterrestrial partner. — \"This isn't ordinary venture capital.\"",
    "enabled": true,
    "created": "2026-05-13T21:40:01.012+00:00",
    "updated": "2026-05-13T21:40:01.012+00:00",
    "awardedCount": 12757551,
    "pastDayAwardedCount": 38784,
    "winRatePercentage": 0.09
  },
  {
    "id": 2744375491202297,
    "name": "Dimensional Dealmaker",
    "description": "Accept the void's offer. — \"...Is this safe?\"",
    "enabled": true,
    "created": "2026-05-13T21:40:19.599+00:00",
    "updated": "2026-05-13T21:40:19.599+00:00",
    "awardedCount": 2944148,
    "pastDayAwardedCount": 12380,
    "winRatePercentage": 0.029
  },
  {
    "id": 2201565160384129,
    "name": "We Are So Back",
    "description": "Complete Dad's mission. — \"Good job, my child.\"",
    "enabled": true,
    "created": "2026-05-13T21:40:49.778+00:00",
    "updated": "2026-05-15T21:08:34.8+00:00",
    "awardedCount": 234498,
    "pastDayAwardedCount": 2254,
    "winRatePercentage": 0.005
  },
  {
    "id": 1821897696658305,
    "name": "Cosmic Farmer",
    "description": "Harvest the cosmic cash vine. — \"Who planted this? ...Actually, I don't care.\"",
    "enabled": true,
    "created": "2026-05-13T21:41:41.813+00:00",
    "updated": "2026-05-13T21:41:41.813+00:00",
    "awardedCount": 2651238,
    "pastDayAwardedCount": 7170,
    "winRatePercentage": 0.017
  },
  {
    "id": 1464971918588968,
    "name": "Good Samaritan",
    "description": "Help the stranger in the sewer and obtain his reward. — \"Now that I helped you, you can help me.\"",
    "enabled": true,
    "created": "2026-05-13T21:42:03.754+00:00",
    "updated": "2026-05-14T16:01:21.252+00:00",
    "awardedCount": 1222691,
    "pastDayAwardedCount": 3421,
    "winRatePercentage": 0.008
  },
  {
    "id": 3444101164439056,
    "name": "Purity",
    "description": "Achieve the purest form of fruit. — \"Can I eat this? ...Should I eat this?\"",
    "enabled": true,
    "created": "2026-05-13T21:52:37.973+00:00",
    "updated": "2026-05-15T21:07:22.34+00:00",
    "awardedCount": 28422,
    "pastDayAwardedCount": 442,
    "winRatePercentage": 0.001
  }
] as const

export const contentUnlocks = [
  {
    "slug": "badges",
    "status": "confirmed",
    "reason": "24 official Roblox badges found.",
    "source": "Roblox badges API"
  },
  {
    "slug": "cosmic-farmer-badge",
    "status": "confirmed",
    "reason": "Official badge lookup for Cosmic Farmer / cosmic cash vine.",
    "source": "Roblox badges API"
  },
  {
    "slug": "good-samaritan-badge",
    "status": "confirmed",
    "reason": "Official badge lookup for Good Samaritan / stranger in the sewer.",
    "source": "Roblox badges API"
  },
  {
    "slug": "purity-fruit",
    "status": "confirmed",
    "reason": "Official badge lookup for Purity / purest form of fruit.",
    "source": "Roblox badges API"
  },
  {
    "slug": "cosmic-cash",
    "status": "confirmed",
    "reason": "Official badge lookup for cosmic cash vine.",
    "source": "Roblox badges API"
  },
  {
    "slug": "lemon-dash",
    "status": "confirmed",
    "reason": "Official badge lookup for LemonDash / Lemon Delivery.",
    "source": "Roblox badges API"
  },
  {
    "slug": "lemon-depot",
    "status": "confirmed",
    "reason": "Official badge lookup for Lemon Depot / Wholesale Lemons.",
    "source": "Roblox badges API"
  },
  {
    "slug": "lemon-trading",
    "status": "confirmed",
    "reason": "Official badge lookup for Lemon Trading.",
    "source": "Roblox badges API"
  },
  {
    "slug": "robotics",
    "status": "confirmed",
    "reason": "Official badge lookup for Lemon Robotics.",
    "source": "Roblox badges API"
  },
  {
    "slug": "powers",
    "status": "confirmed",
    "reason": "Official badge lookup for powers.",
    "source": "Roblox badges API"
  },
  {
    "slug": "alien-investors",
    "status": "confirmed",
    "reason": "Official Roblox data mentions deals / extraterrestrial partner.",
    "source": "Roblox game + badges API"
  },
  {
    "slug": "deals",
    "status": "confirmed",
    "reason": "Official Roblox game description mentions lucrative deals.",
    "source": "Roblox games API"
  },
  {
    "slug": "offline-earnings",
    "status": "confirmed",
    "reason": "Official Roblox game description confirms 100% offline income.",
    "source": "Roblox games API"
  },
  {
    "slug": "redacted-area",
    "status": "confirmed",
    "reason": "Official Roblox game description mentions the redacted area.",
    "source": "Roblox games API"
  }
] as const

export function getVerifiedGameDataDate(): string {
  return 'August 4, 2026'
}
