// Generated by scripts/update-verified-data.mjs
// Official Roblox API data used to unlock verified site content.

export const robloxGame = {
  "id": 7395930870,
  "placeId": 79268393072444,
  "name": "[W2] Sell Lemons 🍋",
  "description": "Sell Lemons 🍋. Make 💵💰🤑.\n\n🍋 Sell Lemons\n💵 Earn lots of cash\n💪 Unlock unique powers\n👽 Make lucrative deals\n🌌 Enter the %^REDACTED*$!\n\n❓ Did you know... You continue to earn 100% of your income offline! 💰\n\n👍 Like the game and join our community to receive absolutely nothing at all!*\n*Except for the knowledge that you made the developers very happy. :)",
  "creatorName": "BloxByte Games",
  "creatorType": "Group",
  "playing": 10175,
  "visits": 460190430,
  "favoritedCount": 490556,
  "maxPlayers": 10,
  "created": "2025-03-17T23:31:17.017Z",
  "updated": "2026-09-25T18:24:57.893Z",
  "genre": "Simulation",
  "subgenre": "Tycoon",
  "canonicalUrlPath": "/games/79268393072444/Sell-Lemons",
  "checkedAt": "2026-09-28T06:18:51.189Z"
} as const

export const robloxVotes = {
  "upVotes": 352489,
  "downVotes": 19940,
  "checkedAt": "2026-09-28T06:18:51.189Z"
} as const

export const robloxBadges = [
  {
    "id": 2839799180453288,
    "name": "Sell Lemons",
    "description": "Buy the Lemon Stand. — \"Lemonade? Nah, we Sell Lemons™.\"",
    "enabled": true,
    "created": "2026-05-13T21:20:19.576+00:00",
    "updated": "2026-05-13T21:20:19.576+00:00",
    "awardedCount": 49326450,
    "pastDayAwardedCount": 222287,
    "winRatePercentage": 0.59
  },
  {
    "id": 798229121420564,
    "name": "Lemon Delivery",
    "description": "Buy LemonDash. — \"Lemons, now conveniently delivered!\"",
    "enabled": true,
    "created": "2026-05-13T21:21:02.153+00:00",
    "updated": "2026-05-13T21:21:02.153+00:00",
    "awardedCount": 44073108,
    "pastDayAwardedCount": 178455,
    "winRatePercentage": 0.474
  },
  {
    "id": 1670501100924687,
    "name": "Wholesale Lemons",
    "description": "Buy Lemon Depot. — \"Time to go wholesale.\"",
    "enabled": true,
    "created": "2026-05-13T21:21:18.539+00:00",
    "updated": "2026-05-13T21:21:18.539+00:00",
    "awardedCount": 34050861,
    "pastDayAwardedCount": 128165,
    "winRatePercentage": 0.34
  },
  {
    "id": 846427648664068,
    "name": "Lemon Trading",
    "description": "Buy Lemon Trading. — \"We're going to BE the market...\"",
    "enabled": true,
    "created": "2026-05-13T21:21:38.422+00:00",
    "updated": "2026-05-13T21:21:38.422+00:00",
    "awardedCount": 20208244,
    "pastDayAwardedCount": 70454,
    "winRatePercentage": 0.187
  },
  {
    "id": 239648239068938,
    "name": "Advanced Lemons",
    "description": "Buy Lemon Labs. — \"People are getting tired of boring old lemons. We must innovate!\"",
    "enabled": true,
    "created": "2026-05-13T21:21:57.039+00:00",
    "updated": "2026-05-13T21:21:57.039+00:00",
    "awardedCount": 9481939,
    "pastDayAwardedCount": 30562,
    "winRatePercentage": 0.081
  },
  {
    "id": 4335425379555311,
    "name": "Really Advanced Lemons",
    "description": "Buy Lemon Robotics. — \"It's the natural progression, really.\"",
    "enabled": true,
    "created": "2026-05-13T21:22:25.757+00:00",
    "updated": "2026-05-13T21:22:25.757+00:00",
    "awardedCount": 5441978,
    "pastDayAwardedCount": 16159,
    "winRatePercentage": 0.043
  },
  {
    "id": 1961627089785243,
    "name": "Lemon-Based Government",
    "description": "Buy Lemon Republic. — \"You know who never pays taxes? The government. ...Wait, I have an idea.\"",
    "enabled": true,
    "created": "2026-05-13T21:23:27.607+00:00",
    "updated": "2026-05-13T21:23:27.607+00:00",
    "awardedCount": 3043053,
    "pastDayAwardedCount": 8035,
    "winRatePercentage": 0.021
  },
  {
    "id": 1703862948070410,
    "name": "Interstellar Lemons",
    "description": "Buy LemonX. — \"Picture this:  Lemons. In. Space.\"",
    "enabled": true,
    "created": "2026-05-13T21:23:45.522+00:00",
    "updated": "2026-05-13T21:23:45.522+00:00",
    "awardedCount": 1516796,
    "pastDayAwardedCount": 4022,
    "winRatePercentage": 0.011
  },
  {
    "id": 4440938742680782,
    "name": "Millionaire",
    "description": "Reach a cash balance of $1,000,000. — \"Who knew lemons were so popular?\"",
    "enabled": true,
    "created": "2026-05-13T21:24:46.557+00:00",
    "updated": "2026-05-13T21:24:46.557+00:00",
    "awardedCount": 41547223,
    "pastDayAwardedCount": 164394,
    "winRatePercentage": 0.437
  },
  {
    "id": 1896495343286922,
    "name": "Billionaire",
    "description": "Reach a cash balance of $1,000,000,000. — \"I'm in the big leagues now!\"",
    "enabled": true,
    "created": "2026-05-13T21:25:10.313+00:00",
    "updated": "2026-05-13T21:25:10.313+00:00",
    "awardedCount": 37366950,
    "pastDayAwardedCount": 143542,
    "winRatePercentage": 0.381
  },
  {
    "id": 3733621909108985,
    "name": "Trillionaire",
    "description": "Reach a cash balance of $1,000,000,000,000. — \"We're just getting started...\"",
    "enabled": true,
    "created": "2026-05-13T21:25:38.477+00:00",
    "updated": "2026-05-13T21:27:56.828+00:00",
    "awardedCount": 31895517,
    "pastDayAwardedCount": 117822,
    "winRatePercentage": 0.313
  },
  {
    "id": 3422658647150754,
    "name": "Decillionaire",
    "description": "Reach a cash balance of $1,000,000,000,000,000,000,000,000,000,000,000. — \"Now that's a lot of zeroes.\"",
    "enabled": true,
    "created": "2026-05-13T21:35:27.148+00:00",
    "updated": "2026-05-13T21:35:27.148+00:00",
    "awardedCount": 7077645,
    "pastDayAwardedCount": 21812,
    "winRatePercentage": 0.058
  },
  {
    "id": 2539875741824246,
    "name": "Vigintillionaire",
    "description": "Reach a cash balance of $1 vigintillion. — \"The zeroes are simply absurd now.\"",
    "enabled": true,
    "created": "2026-05-13T21:35:54.939+00:00",
    "updated": "2026-05-13T21:35:54.939+00:00",
    "awardedCount": 2270506,
    "pastDayAwardedCount": 5844,
    "winRatePercentage": 0.016
  },
  {
    "id": 2219643958762445,
    "name": "Trigintillionaire",
    "description": "Reach a cash balance of $1 trigintillion. — \"...Am I triggering something?\"",
    "enabled": true,
    "created": "2026-05-13T21:36:14.723+00:00",
    "updated": "2026-05-13T21:36:14.723+00:00",
    "awardedCount": 918385,
    "pastDayAwardedCount": 2627,
    "winRatePercentage": 0.007
  },
  {
    "id": 752572950495939,
    "name": "Quattuorquinquagintillionaire",
    "description": "Reach a cash balance of $1 quattuorquinquagintillion. — \"Okay, come on. This can't be a real number.\"",
    "enabled": true,
    "created": "2026-05-13T21:37:44.736+00:00",
    "updated": "2026-05-13T21:37:44.736+00:00",
    "awardedCount": 446235,
    "pastDayAwardedCount": 1640,
    "winRatePercentage": 0.004
  },
  {
    "id": 3040495340594119,
    "name": "Centillionaire",
    "description": "Reach a cash balance of $1 centillion. — \"Another day, another dollar.\"",
    "enabled": true,
    "created": "2026-05-13T21:38:58.774+00:00",
    "updated": "2026-05-13T21:38:58.774+00:00",
    "awardedCount": 41842,
    "pastDayAwardedCount": 175,
    "winRatePercentage": 0
  },
  {
    "id": 4386641676887762,
    "name": "Powered Up",
    "description": "Unlock your first power. — \"Feels a bit tingly. ...I like it.\"",
    "enabled": true,
    "created": "2026-05-13T21:41:07.025+00:00",
    "updated": "2026-05-13T21:41:07.025+00:00",
    "awardedCount": 12675409,
    "pastDayAwardedCount": 43219,
    "winRatePercentage": 0.115
  },
  {
    "id": 1527780026429423,
    "name": "Ultimate Power",
    "description": "Fully unlock every power. — \"POWER! Mwahahaha!\"",
    "enabled": true,
    "created": "2026-05-13T21:41:23.56+00:00",
    "updated": "2026-05-13T21:41:23.56+00:00",
    "awardedCount": 293644,
    "pastDayAwardedCount": 1,
    "winRatePercentage": 0
  },
  {
    "id": 606453995581949,
    "name": "Out of this World",
    "description": "Obtain your first extraterrestrial partner. — \"This isn't ordinary venture capital.\"",
    "enabled": true,
    "created": "2026-05-13T21:40:01.012+00:00",
    "updated": "2026-05-13T21:40:01.012+00:00",
    "awardedCount": 14151329,
    "pastDayAwardedCount": 45149,
    "winRatePercentage": 0.12
  },
  {
    "id": 2744375491202297,
    "name": "Dimensional Dealmaker",
    "description": "Accept the void's offer. — \"...Is this safe?\"",
    "enabled": true,
    "created": "2026-05-13T21:40:19.599+00:00",
    "updated": "2026-05-13T21:40:19.599+00:00",
    "awardedCount": 3305534,
    "pastDayAwardedCount": 8772,
    "winRatePercentage": 0.023
  },
  {
    "id": 2201565160384129,
    "name": "We Are So Back",
    "description": "Complete Dad's mission. — \"Good job, my child.\"",
    "enabled": true,
    "created": "2026-05-13T21:40:49.778+00:00",
    "updated": "2026-05-15T21:08:34.8+00:00",
    "awardedCount": 303967,
    "pastDayAwardedCount": 1385,
    "winRatePercentage": 0.004
  },
  {
    "id": 1821897696658305,
    "name": "Cosmic Farmer",
    "description": "Harvest the cosmic cash vine. — \"Who planted this? ...Actually, I don't care.\"",
    "enabled": true,
    "created": "2026-05-13T21:41:41.813+00:00",
    "updated": "2026-05-13T21:41:41.813+00:00",
    "awardedCount": 2914229,
    "pastDayAwardedCount": 8509,
    "winRatePercentage": 0.023
  },
  {
    "id": 1464971918588968,
    "name": "Good Samaritan",
    "description": "Help the stranger in the sewer and obtain his reward. — \"Now that I helped you, you can help me.\"",
    "enabled": true,
    "created": "2026-05-13T21:42:03.754+00:00",
    "updated": "2026-05-14T16:01:21.252+00:00",
    "awardedCount": 1321756,
    "pastDayAwardedCount": 2894,
    "winRatePercentage": 0.008
  },
  {
    "id": 3444101164439056,
    "name": "Purity",
    "description": "Achieve the purest form of fruit. — \"Can I eat this? ...Should I eat this?\"",
    "enabled": true,
    "created": "2026-05-13T21:52:37.973+00:00",
    "updated": "2026-05-15T21:07:22.34+00:00",
    "awardedCount": 39855,
    "pastDayAwardedCount": 161,
    "winRatePercentage": 0
  },
  {
    "id": 3222464253783609,
    "name": "The Visitors",
    "description": "You were there for an Alien Invasion Event!",
    "enabled": true,
    "created": "2026-08-10T22:48:36.454+00:00",
    "updated": "2026-08-21T23:07:43.403+00:00",
    "awardedCount": 44719,
    "pastDayAwardedCount": 0,
    "winRatePercentage": 0
  },
  {
    "id": 2515489984285035,
    "name": "Out of Breath",
    "description": "Buy the Oxygen Pump. — \"Let’s sell air!?\"",
    "enabled": true,
    "created": "2026-09-17T23:14:19.802+00:00",
    "updated": "2026-09-25T18:14:49.353+00:00",
    "awardedCount": 34508,
    "pastDayAwardedCount": 1535,
    "winRatePercentage": 0.004
  },
  {
    "id": 4097894705863980,
    "name": "Nothing Burger",
    "description": "Buy Fast Oxygen. — \"Mmm, my favorite!\"",
    "enabled": true,
    "created": "2026-09-17T23:15:47.567+00:00",
    "updated": "2026-09-25T18:15:36.86+00:00",
    "awardedCount": 29701,
    "pastDayAwardedCount": 1279,
    "winRatePercentage": 0.003
  },
  {
    "id": 953021062982855,
    "name": "Robot Craze",
    "description": "Buy Oxygen Warehouse. — \"This bubble is getting too big.\"",
    "enabled": true,
    "created": "2026-09-17T23:16:19.307+00:00",
    "updated": "2026-09-25T18:16:00.682+00:00",
    "awardedCount": 24415,
    "pastDayAwardedCount": 1051,
    "winRatePercentage": 0.003
  },
  {
    "id": 886277173604996,
    "name": "Community Bonding",
    "description": "Buy Oxygen Center. — \"WE yes, we are all on this planet together.\"",
    "enabled": true,
    "created": "2026-09-17T23:31:25.743+00:00",
    "updated": "2026-09-25T18:16:27.679+00:00",
    "awardedCount": 17975,
    "pastDayAwardedCount": 809,
    "winRatePercentage": 0.002
  },
  {
    "id": 1974323385543305,
    "name": "A Lotta Oxygen",
    "description": "Buy Oxygen Gardens. — \"Touch grass.\"",
    "enabled": true,
    "created": "2026-09-17T23:31:54.024+00:00",
    "updated": "2026-09-25T18:16:50.323+00:00",
    "awardedCount": 12297,
    "pastDayAwardedCount": 606,
    "winRatePercentage": 0.002
  },
  {
    "id": 1185805778734990,
    "name": "Breezy Vacation",
    "description": "Buy Oxygen Resort. — \"Y'know, I never really liked the hotel prices back home.\"",
    "enabled": true,
    "created": "2026-09-17T23:34:29.117+00:00",
    "updated": "2026-09-25T18:17:04.784+00:00",
    "awardedCount": 7644,
    "pastDayAwardedCount": 504,
    "winRatePercentage": 0.001
  },
  {
    "id": 1763972726483130,
    "name": "Reach to the Sky",
    "description": "Buy Orbital Oxygen Port. — \"They said the sky’s the limit! But uh- what if you’re in space?\"",
    "enabled": true,
    "created": "2026-09-17T23:34:56.337+00:00",
    "updated": "2026-09-25T18:17:21.577+00:00",
    "awardedCount": 3663,
    "pastDayAwardedCount": 319,
    "winRatePercentage": 0.001
  },
  {
    "id": 3657794286254290,
    "name": "Floating Greenhouse",
    "description": "Buy Oxygen Forge. — \"What’s cooler than space? More space!\"",
    "enabled": true,
    "created": "2026-09-18T02:01:51.638+00:00",
    "updated": "2026-09-25T18:17:34.998+00:00",
    "awardedCount": 2639,
    "pastDayAwardedCount": 259,
    "winRatePercentage": 0.001
  },
  {
    "id": 342186871730170,
    "name": "Spaghettification",
    "description": "Discover what’s on the other side of the black hole. — \"THIS LITTLE MANEUVER COST US 51 YEARS!\"",
    "enabled": true,
    "created": "2026-09-18T02:03:06.732+00:00",
    "updated": "2026-09-25T18:17:46.547+00:00",
    "awardedCount": 816,
    "pastDayAwardedCount": 112,
    "winRatePercentage": 0
  },
  {
    "id": 614988805046170,
    "name": "Clarity",
    "description": "Finally have a thought on if you’ve gone too far. — \"I think I finally have enough oxygen to think about it all.\"",
    "enabled": true,
    "created": "2026-09-18T02:04:13.125+00:00",
    "updated": "2026-09-25T18:17:59.815+00:00",
    "awardedCount": 35,
    "pastDayAwardedCount": 4,
    "winRatePercentage": 0
  },
  {
    "id": 1400661931591095,
    "name": "You Peaked",
    "description": "Reach the highest point of the world using the jetpack. — \"Lift off!\"",
    "enabled": true,
    "created": "2026-09-18T02:10:30.33+00:00",
    "updated": "2026-09-25T18:18:09.25+00:00",
    "awardedCount": 1419,
    "pastDayAwardedCount": 111,
    "winRatePercentage": 0
  }
] as const

export const contentUnlocks = [
  {
    "slug": "badges",
    "status": "confirmed",
    "reason": "36 official Roblox badges found.",
    "source": "Roblox badges API"
  },
  {
    "slug": "cosmic-farmer-badge",
    "status": "confirmed",
    "reason": "Official badge lookup for Cosmic Farmer / cosmic cash vine.",
    "source": "Roblox badges API"
  },
  {
    "slug": "good-samaritan-badge",
    "status": "confirmed",
    "reason": "Official badge lookup for Good Samaritan / stranger in the sewer.",
    "source": "Roblox badges API"
  },
  {
    "slug": "purity-fruit",
    "status": "confirmed",
    "reason": "Official badge lookup for Purity / purest form of fruit.",
    "source": "Roblox badges API"
  },
  {
    "slug": "cosmic-cash",
    "status": "confirmed",
    "reason": "Official badge lookup for cosmic cash vine.",
    "source": "Roblox badges API"
  },
  {
    "slug": "lemon-dash",
    "status": "confirmed",
    "reason": "Official badge lookup for LemonDash / Lemon Delivery.",
    "source": "Roblox badges API"
  },
  {
    "slug": "lemon-depot",
    "status": "confirmed",
    "reason": "Official badge lookup for Lemon Depot / Wholesale Lemons.",
    "source": "Roblox badges API"
  },
  {
    "slug": "lemon-trading",
    "status": "confirmed",
    "reason": "Official badge lookup for Lemon Trading.",
    "source": "Roblox badges API"
  },
  {
    "slug": "robotics",
    "status": "confirmed",
    "reason": "Official badge lookup for Lemon Robotics.",
    "source": "Roblox badges API"
  },
  {
    "slug": "powers",
    "status": "confirmed",
    "reason": "Official badge lookup for powers.",
    "source": "Roblox badges API"
  },
  {
    "slug": "alien-investors",
    "status": "confirmed",
    "reason": "Official Roblox data mentions deals / extraterrestrial partner.",
    "source": "Roblox game + badges API"
  },
  {
    "slug": "deals",
    "status": "confirmed",
    "reason": "Official Roblox game description mentions lucrative deals.",
    "source": "Roblox games API"
  },
  {
    "slug": "offline-earnings",
    "status": "confirmed",
    "reason": "Official Roblox game description confirms 100% offline income.",
    "source": "Roblox games API"
  },
  {
    "slug": "redacted-area",
    "status": "confirmed",
    "reason": "Official Roblox game description mentions the redacted area.",
    "source": "Roblox games API"
  }
] as const

export function getVerifiedGameDataDate(): string {
  return 'September 28, 2026'
}
